apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  annotations:
    traefik.ingress.kubernetes.io/whitelist-source-range: "192.168.178.0/24"
    kubernetes.io/ingress.class: traefik  
spec:
  rules:
  - host: grafana.<your-domain-goes-here>
    http:
      paths:
      - backend:
          serviceName: grafana
          servicePort: 80
